name: API Tests

on: [push]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run api-tests via docker-compose
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          docker-compose up --exit-code-from api-tests || true

      - name: Generate Allure report
        run: |
          sudo docker-compose run api-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_API_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
